services:
  - type: web
    name: books-toscrap-flask-app
    repo: https://github.com/Deepak8260/Books-To-Scrape-Flask-App
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    env: python
